config/routes.rb
Rails.application.routes.draw do
  resources :twitters
  post 'twitters/create'
  post 'twitters/search'
  post 'twitters/update'
  root 'twitters#index'
  get '/media' => 'twitters#media'
end

app/models/twitter.rb
class Twitter < ActiveRecord::Base
  
  #ツイートの文字数は140文字以内で空ではない
  validates :tweet, length: {in: 1..140},
                    presence: true
                     
  #ユーザー名は10文字以内で空ではない
  validates :name, length: {in: 1..10},
                   presence: true
  
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/twitters_controller.rb
class TwittersController < ApplicationController
  def index
    @twitters = Twitter.all.order(created_at: :desc)
    @twitter = Twitter.new
    @count = @twitters.count
  end
  
  def post_params
    params.require(:twitter).permit(:name, :tweet, :image)
  end

  def search
    @twitters = Twitter.all.order(created_at: :desc)
    @twitter = Twitter.new
    @twitters = Twitter.where(['name LIKE ?', "%#{params[:keyword]}%"]).order(created_at: :desc)
    @count = @twitters.count
    render "index"
  end
  
  def create
    @twitter = Twitter.new(params.require(:twitter).permit(:name, :tweet, :image))
    if @twitter.save
      redirect_to root_path
    else
      render 'index'
    end
  end
  
  def show
    @twitters = Twitter.all.order(created_at: :desc)
    @twitter = Twitter.new
    @twitter_u = Twitter.find(params[:id])
    @count = @twitters.count
  end
  
  def media
    @twitters = Twitter.all.order(created_at: :desc)
    @twitter = Twitter.new
    @count = @twitters.count
    if @twitter.image.present?
      @twitters = Twitter.order(created_at: :desc)
    end
  end
  
  def update
    @twitter_u = Twitter.find(params[:id])
    @twitter_u.update(params.require(:twitter).permit(:name, :tweet, :image))
    redirect_to root_path
  end
  
  def destroy
    twitter = Twitter.find(params[:id])
    twitter.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitters_helper.rb
module TwittersHelper
end

app/views/layouts/application.html.erb
<html>
  <body>
    <%= render "header" %>
    <div id="wrap">
      <div id="sidebar">
        <%= render "sidebar" %>
      </div>
      <div id="content">
        <%= yield %>
      </div>
    </div>
    <div id="footer">
      <%= render "footer" %>
    </div>
  </body>
</html>

app/views/twitters/_footer.html.erb
<p>
  &copy; 2018 Twitter
  </br>
  <span class="f_link">
    <%= link_to("Twitterについて", 'https://about.twitter.com/ja.html') %>
    &ensp; 
    <%= link_to("ヘルプセンター", 'https://help.twitter.com/ja') %>
    &ensp; 
    <%= link_to("規約", 'https://twitter.com/ja/tos') %>
    &ensp; 
    <%= link_to("プライバシーポリシー", 'https://twitter.com/ja/privacy') %>
    &ensp; 
    <%= link_to("クッキー", 'https://help.twitter.com/ja/rules-and-policies/twitter-cookies') %>
    &ensp; 
    <%= link_to("広告について", 'https://business.twitter.com/ja/help/troubleshooting/how-twitter-ads-work.html') %>
  </span>
</p>

app/views/twitters/_form.html.erb
<%= t.text_area :tweet, label: false, :size => "70", :maxlength => "140", placeholder: 'いまどうしてる？', required: 'required' %>
<label class="name">
  <%= t.input :name, label: false, :maxlength => "10", placeholder: 'ユーザー名', required: 'required' %>
</label>
<label class="file-btn">
  <i class="far fa-image"></i>
  <%= t.input :image, label: false, as: :file %>
</label>

<input id="submit_button" type="submit" name="submit" value="ツイート" />

app/views/twitters/_header.html.erb
<header>
  <title>Twitter</title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <div id="home">
    <a href="/"><i class="fas fa-home"></i> ホーム</a>
  </div>
  
  <input type="button" onclick="location.href='/'" />

  <%= form_tag '/twitters/search', method: :post do %>
    <label id="keyword-btn">
      <%= text_field_tag :keyword, '', placeholder: 'キーワード検索' %>
    </label>
    <button type="submit"></button>
  <% end %>
  
  
    <div id="square_btn"><label for="popup-on">ツイート</label></div>
  
  <input type="checkbox" id="popup-on"/>
  <div class="popup">
    <div class="t">ツイートする</div>
    <a class="close" href="#">&times;</a>
    <p>
      <%= simple_form_for @twitter, :url => {action: :create} do |t| %>
        <%= render "form", t: t %>
      <% end %>
    </p>
  </div>
</header>  

<div id="about_img"></div>
<div id="header2">
  <div id="status">
    ツイート
    </br>
    <span id="count"><%= @count %></span>
    </br>
    <div id="status-bar"></div>
  </div>
</div>

<label for="imgpop-on">
  <div class="circle">
    <%= image_tag 'kinki.jpg', :class => "img-round" %>
  </div>
</label>

<input type="checkbox" id="imgpop-on"/>
<div class="imgpop">
  <label for="imgpop-on" class="icon-close">×</label>
  <div class="imgpop-content">
    <%= image_tag 'kinki.jpg', :class => "imgpop-round" %>
  </div>
</div>

app/views/twitters/_show.erb
<div class = "posts-index-item" >
  <span class="user">
    <b><%= link_to(t.name, twitter_path(t)) %></b>
    &ensp; 
  </span>
  <span class="tuser">
    @<%= Romaji.kana2romaji "#{t.name}" %>
  </span>
  &ensp;
  <span class="post-time">
    <% time = t.created_at.strftime("%Y年%m月%d日")  %>
    <%= link_to(time, twitter_path(t)) %>
  </span>
  </br>
  <span class="tweet">
    <%= link_to(t.tweet, twitter_path(t)) %>
  </span>
  </br>
  <% if t.image.present? %>
    <%= link_to twitter_path(t) do %>
      <%= image_tag t.image.url, :size => '300x300' %>
    <% end %>
    </br>
  <% end %>
</div>

app/views/twitters/_sidebar.html.erb
<span id="title">
  <%= link_to("近畿大学", root_path) %>
</span>
</br>
<span class="tuser">
  @<%= link_to("kinkidaigakuPR", root_path) %>
</span>
</br></br>
近畿大学総務部広報室のTwitter公式アカウントです。
近畿大学ホームページの更新情報を中心に、大学に関する情報を発信していきます。
個別DMでのお問い合わせには返信を行っておりませんので、ご了承ください。
</br></br>

<span class="iro">
  <i class="fas fa-map-marker-alt"></i>&ensp;大阪府東大阪市
  </br>
  <i class="fas fa-link"></i>
  <span class="link"><%= link_to("instagram.com/kinkidaigakupr/", "https://www.instagram.com/kinkidaigakupr/") %></span>
  </br>
  <i class="far fa-calendar-alt"></i>&ensp;2010年12月に登録
</span>

<label for="popup-on">
  <div id="s_btn">ツイート</div>
</label>
<input type="checkbox" id="popup-on"/>
<div class="popup">
  <div class="t">ツイートする</div>
  <a class="close" href="#">&times;</a>
  <p>
    <%= simple_form_for @twitter, :url => {action: :create} do |t| %>
      <%= render "form", t: t %>
    <% end %>
  </p>
</div>

app/views/twitters/index.html.erb
<div class = "c">
  ツイート
  &emsp;
  <span class = "font_c"><%= link_to("メディア", media_path) %></span>
</div>

<% @twitters.each do |t| %>
  <%= render "show", t: t %>
<% end %>

app/views/twitters/media.html.erb
<div class = "c">
  <span class = "font_c"><%= link_to("ツイート", root_path) %></span>
  &emsp;
  メディア
</div>
    
<% @twitters.each do |t| %>
  <% if t.image.present? %>
    <%= render "show", t: t %>
  <% end %>
<% end %>

app/views/twitters/show.html.erb
<div class = "c">
  <span class = "font_c"><%= link_to("ツイート", root_path) %></span>
  &emsp;
  <span class = "font_c"><%= link_to("メディア", media_path) %></span>
</div>

<div class = "posts-edit-item" >
  
  <label for="popup-on2">
    <div class="edit">&or;</div>
  </label>
  <input type="checkbox" id="popup-on2"/>
  <div class="popup">
    <div class="t">ツイートを編集する</div>
    <a class="close" href="#">&times;</a>
    <p>
      <%= simple_form_for @twitter_u, :url => {action: :update} do |t| %>
        <%= render "form", t: t %>
        &ensp;
        <%= link_to twitter_path(@twitter_u), :method => :delete do %>
          <div class="delete-btn"><i class="fas fa-trash-alt"></i></div>
        <% end %>
      <% end %>
    </p>
  </div>
  
  
  <div class="show">
    <b><%= @twitter_u.name %></b> 
    </br> 
    <span class="tuser">
        @<%= Romaji.kana2romaji "#{@twitter_u.name}" %>
    </span>
    &ensp;
    </br>
    <p><%= @twitter_u.tweet %></p>
    <% if @twitter_u.image.present? %>
      <%= image_tag @twitter_u.image.url, :size => '320x320' %>
    <% end %>
    </br></br>
    <span class="post-time">
      <%= @twitter_u.created_at.strftime("%H:%M") %> - <%= @twitter_u.created_at.strftime("%Y年%m月%d日")  %>
    </span>
    </br>
  </div>
</div>